env:
  global:
    - CC_TEST_REPORTER_ID=63dc7e6fac46473b6a48dcc66e1490e66085af6e31270c0611587000a8072357
language: node_js
node_js:
  - "stable"
script:
  - yarn test
  - yarn build
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
